### ISSUE TITLE
protected rooms

### ISSUE THREAD

**Issue by rlahmaidi** [DeadlineTeam/ft_trandenden#13]
user can't create a protected room without a password, but no message shows up to tell him what to do

**Comment by ELORCHI** [comment]
are you sure this case is not handled?
I created a branch roomDtoValidation, especially for this case and it was reviewed and merged by @xatify
please,  provide us with more details about this error issue and make sure you are testing the develop branch, not the master.

here is the code from create-room.dto
`
	@ValidateIf((object: any) => object.visibility !== undefined && object.visibility === 'Protected')
	@IsNotEmpty({
		message: 'Password is required for protected rooms',
		when: (object: any) => object.password !== undefined
	  } as ValidationOptions)
	password: string;
`

**Comment by rlahmaidi** [comment]
what you said is right and working fluently from backend, users can't create a protected room without a password. but we don't tell the user what the problem or what he should do. the screen just seems to be freezing when you try to save a protected room without entering a password. we need just to show him a pop-up telling him that he should provide a password. that's it

**Comment by ELORCHI** [comment]
if it is a frontend problem refer to @Odin-leet or @xatify

**Comment by Odin-leet** [comment]
it s working for me brother , check if u pulled the last version of the project

**Comment by xatify** [comment]
the error I get in front with th new Dto validation seems not to work, so we will use the old version 
no Dto validation
