### ISSUE TITLE
Myprofile

### ISSUE THREAD

**Issue by rlahmaidi** [DeadlineTeam/ft_trandenden#15]
.The level of the player(up-left under player profile picture) is being casted to integer somehow (i.e 0 will show up for a player with 0.75level and for a player with 0.25level …..), so either fix it to show the exact level as a float or make the level grows by an integer(1 for example).
. In STATS, win rate should be casted to int , we don’t want our user win rate to be 28.312333556656%

<img width="931" alt="Screen Shot 2023-01-08 at 6 03 03 AM" src="https://user-images.githubusercontent.com/84911774/211181455-e7aa4e59-6b41-40da-bc61-254488ff907e.png">

**Comment by Odin-leet** [comment]
fixed
