### ISSUE TITLE
To change in Dashboard

### ISSUE THREAD

**Issue by rlahmaidi** [DeadlineTeam/ft_trandenden#18]
@ELORCHI   @Odin-leet 
. Winrate should be multiplayed by 100 and casted into int.
. Update the w/l  with (number_of_match_won / total_matches) , cause it is always 12/12ft
<img width="1533" alt="Screen Shot 2023-01-08 at 10 33 55 AM" src="https://user-images.githubusercontent.com/84911774/211189556-d655196e-5499-456e-9e67-f19e428f4307.png">

**Comment by ELORCHI** [comment]
we talked about this me and @Odin-leet and we decided that it will be handled by the frontend

**Comment by rlahmaidi** [comment]
fixed
