### ISSUE TITLE
problem when disconnecting and reconnecting from an authenticated user

### ISSUE THREAD

**Issue by rlahmaidi** [DeadlineTeam/ft_trandenden#26]
when an authenticated user logs out and logs in again his online status in database will still be set to false, and thus he can't play a game , he can't send a message .
NOTE: when hitting the refresh button the user will be set online in database now and can play and chat as normal user

https://user-images.githubusercontent.com/84911774/211462806-2e15c8ad-c161-4878-83ca-3533163db0bf.mp4

**Comment by ELORCHI** [comment]
Fixed
