### ISSUE TITLE
rooms serach

### ISSUE THREAD

**Issue by rlahmaidi** [DeadlineTeam/ft_trandenden#7]
1-User can only see the rooms he is a member in, so how he is supposed to search for other rooms,

2 - user can’t search rooms he is member in => doesn’t make sense, unless it is  a feature?

**Comment by xatify** [comment]
- the search room displays only the public or protected room the user can join
- for the moment if he doen't have the first character of that room he wont find any rooms
- we will recode that part to display all the rooms available to join and the user can then filter by name

**Comment by xatify** [comment]
fixed!!
